### ISSUE TITLE
No such group: "lsp_rust_analyzer"

### ISSUE THREAD

**Issue by Gl00ria** [danielnehrig/nvim#24] opened 2024-06-22 17:04 UTC
Hi, thanks for the amazing effort for this config.

I'm getting the following error with `.rs` files
`.config/nvim/lua/config/core/autocmd.lua:80: Vim:E367: No such group: "lsp_rust_analyzer"
stack traceback:
	[C]: in function 'nvim_del_augroup_by_name'
	/home/USERNAME/.config/nvim/lua/config/core/autocmd.lua:80: in function </home/USERNAME/.config/nvim/lua/config/core/autocmd.lua:78>
	[C]: in function 'nvim_exec_autocmds'
	/usr/share/nvim/runtime/lua/vim/lsp.lua:391: in function </usr/share/nvim/runtime/lua/vim/lsp.lua:389>
Client rust_analyzer quit with exit code 1 and signal 0.`

**Comment by danielnehrig** [comment] 2024-06-26 20:06
Thanks for opening an issue

I've never encountered that issue with the config so far do you mind sharing the commit you're on as well as nvim Version and lazy lockfile 

Can only assume right now what the problem is also line numbers from your error log do not line up with current master either you made changes in it which I can not support or it's a older commit

**Comment by danielnehrig** [comment] 2024-06-26 20:11
Also is the rust analyser working at all because it says it's exiting and I can infer from the error log that it's calling the AutoCmd for lsp detach
For this detach to fail it means that the autocmd LspAttach for the inlayhints have not been executed and augroups are not created

**Comment by danielnehrig** [comment] 2024-06-26 20:18
I pushed a change pull and test 

I assume you're running an old version of rust analyser without documentHighlight support

**Comment by Gl00ria** [comment] 2024-06-27 07:42
Thanks and appreciate your time,
 
its working perfectly now, also regarding the "line numbers doesn't line up with yours" I just added some comments that is why.

**Comment by danielnehrig** [comment] 2024-06-27 13:52
Thanks for confirming it works closing issue

**Closed as completed** 2024-06-27 13:52 UTC
